[tasks.run]
workspace = false
dependencies = ["build", "install-simple-http-server", "read-example-arg"]
script_runner = "@duckscript"
script = [
    """
    example = get_env EXAMPLE
    cd ${example}
    exec simple-http-server --index -- www
    """
]

[tasks.install-simple-http-server]
install_crate = { crate_name = "simple-http-server", binary = "simple-http-server", test_arg = ["--version"] }

[tasks.build]
clear = true
workspace = false
dependencies = ["install-wasm-pack", "read-example-arg"]
script_runner = "@duckscript"
script = [
    """
    example = get_env EXAMPLE
    if is_empty ${example}
        trigger_error "no example given"
    end

    cd ${example}
    rm -r www
    exec wasm-pack build --no-typescript --out-dir www --target web

    files = array "index.html"
    for file in ${files}
        cp static/${file} www/${file}
    end
    """
]

[tasks.read-example-arg]
workspace = false
script_runner = "@duckscript"
script = [
    """
    if is_defined EXAMPLE
        exit
    end

    args = get_env CARGO_MAKE_TASK_ARGS
    args = split ${args} ;
    example = array_get ${args} 0
    if is_empty ${example}
        trigger_error "no example given"
    end

    set_env EXAMPLE ${example}
    """
]
